# Generated by Django 5.1.4 on 2024-12-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('Informatyk', 'Informatyk'), ('Zarządzanie', 'Zarządzanie')], default='Informatyk', max_length=15),
        ),
    ]
